services:
  - type: worker
    name: audio-metadata-bot
    env: python

    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt

    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: MAX_INPUT_MB
        value: 20

      - key: EXTRA_VOICE_RANGES
        value: 08:53-10:40

      - key: EXTRA_VOICE_ACTION
        value: reduce
